# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('descritpion', models.TextField(max_length=1000)),
                ('date_from', models.CharField(max_length=255)),
                ('date_to', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining_users', models.ManyToManyField(default=None, related_name='joined_trips', to='login_reg.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_id', to='login_reg.User')),
            ],
        ),
    ]
